[CAMERA][MSM] Fix missing include path for cam_trace.h
Added missing include path for cam_utils to resolve compilation error
due to cam_trace.h not being found. This change ensures that the
cam_trace.h file located in drivers/media/platform/msm/camera/cam_utils/
is properly included during the build process.

Fixes: ./include/trace/define_trace.h:89:10: fatal error: './cam_trace.h' file not found